2024-09-09 09:53:33,793 INFO    MainThread:30124 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2024-09-09 09:53:33,793 INFO    MainThread:30124 [wandb_setup.py:_flush():76] Configure stats pid to 30124
2024-09-09 09:53:33,793 INFO    MainThread:30124 [wandb_setup.py:_flush():76] Loading settings from /Users/gabrielslotnisky/.config/wandb/settings
2024-09-09 09:53:33,793 INFO    MainThread:30124 [wandb_setup.py:_flush():76] Loading settings from /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/settings
2024-09-09 09:53:33,793 INFO    MainThread:30124 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-09 09:53:33,793 INFO    MainThread:30124 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-09 09:53:33,793 INFO    MainThread:30124 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-09 09:53:33,794 INFO    MainThread:30124 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-09 09:53:33,794 INFO    MainThread:30124 [wandb_init.py:_log_setup():524] Logging user logs to /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/run-20240909_095333-qj5p0he5/logs/debug.log
2024-09-09 09:53:33,794 INFO    MainThread:30124 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/run-20240909_095333-qj5p0he5/logs/debug-internal.log
2024-09-09 09:53:33,795 INFO    MainThread:30124 [wandb_init.py:init():607] calling init triggers
2024-09-09 09:53:33,795 INFO    MainThread:30124 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-09-09 09:53:33,795 INFO    MainThread:30124 [wandb_init.py:init():657] starting backend
2024-09-09 09:53:33,795 INFO    MainThread:30124 [wandb_init.py:init():661] setting up manager
2024-09-09 09:53:33,803 INFO    MainThread:30124 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-09-09 09:53:33,803 INFO    MainThread:30124 [wandb_init.py:init():669] backend started and connected
2024-09-09 09:53:33,813 INFO    MainThread:30124 [wandb_run.py:_label_probe_notebook():1338] probe notebook
2024-09-09 09:53:33,813 INFO    MainThread:30124 [wandb_run.py:_label_probe_notebook():1348] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-09 09:53:33,813 INFO    MainThread:30124 [wandb_init.py:init():764] updated telemetry
2024-09-09 09:53:33,838 INFO    MainThread:30124 [wandb_init.py:init():797] communicating run to backend with 90.0 second timeout
2024-09-09 09:53:34,182 ERROR   MainThread:30124 [wandb_init.py:init():823] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-09-09 09:53:34,182 ERROR   MainThread:30124 [wandb_init.py:init():1235] error in wandb.init()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1225, in init
    return wi.init()
           ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 829, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
